import openpyxl

TOLERANCE = 0.01


def parse_order_confirmation_xlsx(file) -> dict:
    """Parse an order-confirmation xlsx generated by order_utils.generate_invoice_pattern_file."""
    wb = openpyxl.load_workbook(file, data_only=True)
    ws = wb.worksheets[0]

    order_id = None
    order_date = None
    bestellliste = None
    header_row = None

    for row in ws.iter_rows(min_row=1, max_row=ws.max_row):
        label = row[0].value
        if label == "Bestellung Nr.:":
            order_id = row[1].value
        elif label == "Bestelldatum:":
            order_date = row[1].value
        elif label == "Bestellliste:":
            bestellliste = row[1].value
        elif label == "Pos":
            header_row = row[0].row
            break

    items = []
    if header_row:
        for row in ws.iter_rows(min_row=header_row + 1, max_row=ws.max_row):
            pos = row[0].value
            if not isinstance(pos, (int, float)):
                break
            items.append({
                "product_number": str(row[3].value),
                "product_name": row[4].value,
                "unit": row[2].value,
                "quantity": float(row[1].value),
                "unit_price": float(row[5].value),
                "vat_percent": float(row[6].value),
                "line_total": float(row[7].value),
            })

    return {
        "order_id": order_id,
        "order_date": order_date,
        "bestellliste": bestellliste,
        "items": items,
    }


def compare_order_to_invoice(order_items: list[dict], invoice_items: list[dict]) -> list[dict]:
    """Compare ordered items vs. invoiced items by product_number. Returns a list of
    per-product comparison rows with a `status` and human-readable `notes`."""
    by_number_order = {}
    for it in order_items:
        by_number_order.setdefault(str(it["product_number"]), []).append(it)

    by_number_invoice = {}
    for it in invoice_items:
        by_number_invoice.setdefault(str(it["product_number"]), []).append(it)

    all_numbers = sorted(set(by_number_order) | set(by_number_invoice), key=lambda x: (len(x), x))

    results = []
    for num in all_numbers:
        ordered = by_number_order.get(num)
        invoiced = by_number_invoice.get(num)

        if ordered and not invoiced:
            o = ordered[0]
            results.append({
                "product_number": num,
                "product_name": o["product_name"],
                "status": "❌ Missing from invoice",
                "ordered_qty": o["quantity"],
                "invoiced_qty": None,
                "ordered_price": o["unit_price"],
                "invoiced_price": None,
                "ordered_total": o["line_total"],
                "invoiced_total": None,
                "diff": -o["line_total"],
                "notes": "Ordered but never billed — vendor may still owe this item.",
            })
            continue

        if invoiced and not ordered:
            v = invoiced[0]
            results.append({
                "product_number": num,
                "product_name": v["product_name"],
                "status": "⚠️ Not ordered / unexpected charge",
                "ordered_qty": None,
                "invoiced_qty": v["quantity"],
                "ordered_price": None,
                "invoiced_price": v["unit_price"],
                "ordered_total": None,
                "invoiced_total": v["line_total"],
                "diff": v["line_total"],
                "notes": "Billed but not part of the order — verify this charge is legitimate.",
            })
            continue

        o = ordered[0]
        v = invoiced[0]
        notes = []
        status = "✅ OK"

        if abs(o["quantity"] - v["quantity"]) > TOLERANCE:
            notes.append(f"Quantity differs: ordered {o['quantity']:g} vs invoiced {v['quantity']:g}")
            status = "⚠️ Quantity mismatch"
        if abs(o["unit_price"] - v["unit_price"]) > TOLERANCE:
            notes.append(f"Unit price differs: ordered €{o['unit_price']:.2f} vs invoiced €{v['unit_price']:.2f}")
            status = "🚨 Price mismatch"
        if abs(o["vat_percent"] - v["vat_percent"]) > TOLERANCE:
            notes.append(f"VAT % differs: ordered {o['vat_percent']:g}% vs invoiced {v['vat_percent']:g}%")
            if status == "✅ OK":
                status = "⚠️ VAT mismatch"

        results.append({
            "product_number": num,
            "product_name": v["product_name"],
            "status": status,
            "ordered_qty": o["quantity"],
            "invoiced_qty": v["quantity"],
            "ordered_price": o["unit_price"],
            "invoiced_price": v["unit_price"],
            "ordered_total": o["line_total"],
            "invoiced_total": v["line_total"],
            "diff": round(v["line_total"] - o["line_total"], 2),
            "notes": "; ".join(notes) if notes else "Matches order.",
        })

    return results


def build_dispute_message(invoice_data: dict, order_data: dict, comparison: list[dict]) -> str:
    """Plain-text message summarizing every flagged discrepancy, ready to send to the vendor."""
    flagged = [row for row in comparison if row["status"] != "✅ OK"]

    lines = [
        f"Subject: Invoice discrepancy — Invoice {invoice_data['invoice_number']} "
        f"({invoice_data['invoice_date']})",
        "",
        "Hello,",
        "",
        f"We've reviewed invoice {invoice_data['invoice_number']} dated {invoice_data['invoice_date']} "
        f"against our order #{order_data['order_id']} ({order_data['order_date']}) and found the "
        f"following discrepanc{'y' if len(flagged) == 1 else 'ies'}:",
        "",
    ]

    for row in flagged:
        lines.append(f"- {row['product_name']} (#{row['product_number']}): {row['notes']}")
        ordered = (
            f"{row['ordered_qty']:g} x €{row['ordered_price']:.2f} = €{row['ordered_total']:.2f}"
            if row["ordered_qty"] is not None else "not part of our order"
        )
        invoiced = (
            f"{row['invoiced_qty']:g} x €{row['invoiced_price']:.2f} = €{row['invoiced_total']:.2f}"
            if row["invoiced_qty"] is not None else "not billed"
        )
        lines.append(f"    Ordered: {ordered}")
        lines.append(f"    Invoiced: {invoiced}")
        lines.append("")

    invoice_netto = invoice_data.get("netto_total")
    invoice_brutto = invoice_data.get("brutto_total")
    order_items = order_data.get("items", [])
    order_netto = round(sum(it["line_total"] for it in order_items), 2) if order_items else None

    if invoice_brutto is not None and invoice_netto is not None:
        lines.append(f"Invoice totals: Netto €{invoice_netto:.2f}, Brutto €{invoice_brutto:.2f}")
    if order_netto is not None:
        lines.append(f"Our order total (Netto): €{order_netto:.2f}")
    lines.append("")

    lines.append("Please review and either issue a corrected invoice or confirm the reason for these differences.")
    lines.append("")
    lines.append("Thank you,")
    lines.append("Habib RFC Mannheim GmbH")

    return "\n".join(lines)
